var windowsKB, ngn_v, gn_c = new Array, gn_cUni = new Array, gn_v = new Array, gn_vUni = new Array, gn_vmUni = new Array, specialgn_c = new Array, specialgn_cUni = new Array, gn_scUni = new Array, gn_sc = new Array;





function startTextSf() { windowsKB = document.getElementById("box2").value, document.getElementById("box3").value = writeSinhalaWindowsKB(windowsKB); var g = document.getElementById("box2").value; document.getElementById("box4").value = toisiwara(g) }


function writeSinhalaWindowsKB(g) { return g = s(g, /,/g, "￦"), g = s(g, /\./g, "¡"), g = s(g, /\(/g, "￫"), g = s(g, /\)/g, "￩"), g = s(g, /%/g, "ￕ"), g = s(g, /\//g, "$"), g = s(g, /–/g, "ￔ"), g = s(g, /\?/g, "ￓ"), g = s(g, /!/g, "ￒ"), g = s(g, /\=/g, "ￏ"), g = s(g, /\'/g, "ￎ"), g = s(g, /\+/g, "ￍ"), g = s(g, /\:/g, "ￌ"), g = s(g, /\÷/g, "ￋ"), g = s(g, /\;/g, "ﾶ"), g = s(g, /ත්‍රෛ/g, "ff;%"), g = s(g, /ශෛ/g, "ffY"), g = s(g, /චෛ/g, "ffp"), g = s(g, /ජෛ/g, "ffc"), g = s(g, /කෛ/g, "ffl"), g = s(g, /මෛ/g, "ffu"), g = s(g, /පෛ/g, "ffm"), g = s(g, /දෛ/g, "ffo"), g = s(g, /තෛ/g, "ff;"), g = s(g, /නෛ/g, "ffk"), g = s(g, /ධෛ/g, "ffO") }


function toisiwara(g) { return g = s(g, /කෛ/g, "»»Y"), g = s(g, /වෛ/g, "»»{"), g = s(g, /චෛ/g, "»»a"), g = s(g, /දෛ/g, "»»n"), g = s(g, /තෛ/g, "»»l"), g = s(g, /නෛ/g, "»»p"), g = s(g, /මෛ/g, "»»v"), g = s(g, /පෛ/g, "»»r"), g = s(g, /ශෛ/g, "»»|"), g = s(g, /ත්‍රෛ/g, "»»l±"), g = s(g, /ජෛ/g, "»»c"), g = s(g, /ධෛ/g, "»»o"), g = s(g, /ක්‍යෝ/g, "»Y³£Š"), g = s(g, /ඛ්‍යෝ/g, "»Z³£Š"), g = s(g, /ප්‍රෞ/g, "»r±°"), g = s(g, /ඡ්‍යෝ/g, "»b³£Š"), g = s(g, /ඪ්‍යෝ/g, "»i³£Š"), g = s(g, /ඝ්‍යෝ/g, "»]³£Š"), g = s(g, /ළ්‍යෝ/g, "»…³£Š"), g = s(g, /ඵ්‍යෝ/g, "»s³£Š"), g = s(g, /ඨ්‍යෝ/g, "»g³£Š"), g = s(g, /ශ්‍යෝ/g, "»|³£Š"), g = s(g, /ෂ්‍යෝ/g, "»}³£Š"), g = s(g, /ක්‍ෂ්‍යෝ/g, "»³£Š"), g = s(g, /බ්‍යෝ/g, "»t³£Š"), g = s(g, /ච්‍යෝ/g, "»a³£Š"), g = s(g, /ඩ්‍යෝ/g, "»³£Š"), g = s(g, /ෆ්‍යෝ/g, "»‡³£Š") }


function doGnConvert(g) { for (var s, n, f, _ = 0; _ < specialgn_c.length; _++)g = assignChars(g, specialgn_c[_], specialgn_cUni[_]); for (var a = 0; a < gn_scUni.length; a++)for (var i = 0; i < gn_c.length; i++)s = gn_c[i] + gn_sc[a], f = gn_cUni[i] + gn_scUni[a], n = makeReplaceExp(s), g = assignChars(g, n, f); for (_ = 0; _ < gn_c.length; _++) { for (var c = 0; c < gn_v.length; c++)s = gn_c[_] + "r" + gn_v[c], f = gn_cUni[_] + "්‍ර" + gn_vmUni[c], n = makeReplaceExp(s), g = assignChars(g, n, f); s = gn_c[_] + "r", f = gn_cUni[_] + "්‍ර", n = makeReplaceExp(s), g = assignChars(g, n, f) } for (_ = 0; _ < gn_c.length; _++)for (c = 0; c < ngn_v; c++)s = gn_c[_] + gn_v[c], f = gn_cUni[_] + gn_vmUni[c], n = makeReplaceExp(s), g = assignChars(g, n, f); for (_ = 0; _ < gn_c.length; _++)n = makeReplaceExp(gn_c[_]), g = assignChars(g, n, gn_cUni[_] + "්"); for (_ = 0; _ < gn_v.length; _++)n = makeReplaceExp(gn_v[_]), g = assignChars(g, n, gn_vUni[_]); return g } gn_vUni[0] = "ඌ", gn_v[0] = "oo", gn_vmUni[0] = "ූ", gn_vUni[1] = "ඕ", gn_v[1] = "o\\)", gn_vmUni[1] = "ෝ", gn_vUni[2] = "ඕ", gn_v[2] = "oe", gn_vmUni[2] = "ෝ", gn_vUni[3] = "ආ", gn_v[3] = "aa", gn_vmUni[3] = "ා", gn_vUni[4] = "ආ", gn_v[4] = "a\\)", gn_vmUni[4] = "ා", gn_vUni[5] = "ඈ", gn_v[5] = "Aa", gn_vmUni[5] = "ෑ", gn_vUni[6] = "ඈ", gn_v[6] = "A\\)", gn_vmUni[6] = "ෑ", gn_vUni[7] = "ඈ", gn_v[7] = "ae", gn_vmUni[7] = "ෑ", gn_vUni[8] = "ඊ", gn_v[8] = "ii", gn_vmUni[8] = "ී", gn_vUni[9] = "ඊ", gn_v[9] = "i\\)", gn_vmUni[9] = "ී", gn_vUni[10] = "ඊ";